# Generated by Django 5.2 on 2025-04-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sustainability_score', models.PositiveIntegerField(help_text='Score from 1-100 showing environmental impact')),
                ('image', models.ImageField(upload_to='products/')),
                ('solar_powered', models.BooleanField(default=True)),
                ('discount_per_sun_point', models.DecimalField(decimal_places=2, default=1.0, help_text='Discount amount per sun point in currency', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
