# Generated by Django 5.0.4 on 2025-05-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sustainability_score',
            field=models.PositiveIntegerField(default=0, help_text='Score from 1-100 showing environmental impact'),
        ),
    ]
