# Generated by Django 5.2 on 2025-05-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='property',
            field=models.JSONField(blank=True, default=dict, help_text='Key-value info about the product, like dimensions, power, etc.'),
        ),
    ]
