# Generated by Django 5.2 on 2025-04-30 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonFootprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2_saved_kg', models.DecimalField(decimal_places=2, help_text='CO2 saved in kg compared to non-solar alternative', max_digits=10)),
                ('water_saved_liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('energy_saved_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ImpactReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_co2_saved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_energy_saved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equivalent_trees_planted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
